### ISSUE TITLE
demo fails to start

### ISSUE THREAD

**Issue by ajs6f** [genomehubs/demo#4]
Hi, I'm trying to set up a demo of GenomeHub as described [here](https://genomehubs.gitbooks.io/genomehubs/content/demo.html) but startup is failing out with a problem finding a config file:

```
awk: cannot open /ensembl/conf/database.ini (No such file or directory)
```
Here's the [whole log](https://gist.github.com/ajs6f/a51934d9872f37fd1f0878c3519b5772) for review. I'm assuming that the `awk` calls are getting made inside some Dockerfile or setup script in one of the many images that are involved here?

Thanks for any help!

**Comment by sujaikumar** [comment]
Thanks for pasting the whole log. Yes, you're right - it's all happening inside the docker images. I'll have a look through and let you know if I get the same problem

**Comment by sujaikumar** [comment]
Just checking - did you do a git clone into your home directory?

The import.sh script makes the assumption that you were in ~ when you did `git clone https://github.com/genomehubs/demo.git`

That's why it tries to mount the docker folders to ~/demo/genomehubs-import/ensembl/conf in demo/import.sh line 30.

If you've git cloned into a different folder than ~/demo, just do a find and replace for ~/demo in import.sh.

Hope this helps

**Comment by ajs6f** [comment]
Yep. that seems to be it. With respect, that seems like a questionable assumption to me-- once this setup run completes (assuming successful completion) I'll send a PR for that.

**Comment by sujaikumar** [comment]
I agree. It was an assumption of convenience :-)
